### PR TITLE
Migrations & Seeds

### PR DESCRIPTION
**Pull request by noxify**
* Convert of the SQL Dumps to laravel migrations
* added seeds for Roles + Permissions
* Added seed for settings table

### CODE REVIEW

**Comment by tabacitu** [comment]
This is great, Marcus. Thanks! 

I've merged it, but I think the https://github.com/tabacitu/settings repository might be a better place for the settings migration and seeds you've created. It isn't a black-or-white thing, though, since that package is a required component in Dick. We could just keep all seeds and migrations here, so they could be easily run.

What do you think, should I move them in Settings? 

@Ghitu , what do you think?

**Comment by Ghitu** [comment]
I think you should move them to Settings, makes more sense. Also @noxify I think Integer fields should be unsigned where no negative values are stored.

**Comment by noxify** [comment]
@tabacitu - yes, to move the settings migrations to the settings package makes more sense.
I have forked only the "dick" repo and didn't checked the composer.json.
Otherwise I had created separate PRs.

@Ghitu - yes, you're right - it makes no sense to save an negative id (as example).
Should I change it or can you do this?

Anyway - thanks for this awesome package.

**Comment by tabacitu** [comment]
Done and done.

Glad you like it. Please continue to help out ;-)

**Pull request merged**
